name = "d1"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[durable_objects]
bindings = [{ name = "STREAMS", class_name = "StreamDO" }]

[[migrations]]
tag = "v1"
new_classes = ["StreamDO"]

[[d1_databases]]
binding = "DB"
database_name = "streams-db"
database_id = "local"
